stages:
  - build
  - test
  - sast
  - dast
  - review
  - deploy

# Variáveis de ambiente
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_FILE: docker-compose.yaml
  APP_URL: "http://localhost:5000"

# Cache para acelerar builds
cache:
  paths:
    - .docker

# Etapa de Build
build:
  stage: build
  script:
    - docker build -t my-app .
  tags:
    - docker

