stages:
  - build
  - test
  - sast
  - dast
  - review
  - deploy

# Variáveis de ambiente
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_FILE: docker-compose.yaml
  APP_URL: "http://localhost:5000"

# Cache para acelerar builds
cache:
  paths:
    - .docker

# Etapa de Build
build:
  stage: build
  script:
    - docker build -t my-app .
  tags:
    - docker

# Etapa de Testes Automatizados
test:
  stage: test
  script:
    - docker-compose up -d
    - docker exec my-app pytest  # Substitua pelo comando de teste adequado
    - docker-compose down
  tags:
    - docker

# Etapa de Análise Estática de Código (SAST)
sast:
  stage: sast
  image: python:3.9
  script:
    - pip install bandit
    - bandit -r .
  tags:
    - docker

# Etapa de Análise de Dependências
dependency-check:
  stage: sast
  image: owasp/dependency-check
  script:
    - dependency-check.sh --project my-app --out .
  artifacts:
    paths:
      - dependency-check-report.html
  tags:
    - docker

# Etapa de Análise Dinâmica de Segurança (DAST)
dast:
  stage: dast
  image: owasp/zap2docker-stable
  services:
    - name: docker:19.03.12-dind
  script:
    - docker-compose up -d
    - docker run -t owasp/zap2docker-stable zap-baseline.py -t $APP_URL
    - docker-compose down
  artifacts:
    paths:
      - zap_report.html
  tags:
    - docker

# Revisão de Merge Requests
review:
  stage: review
  script:
    - docker-compose up -d
    - echo "Ambiente de revisão criado em $APP_URL"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $APP_URL
    on_stop: stop_review
  tags:
    - docker

# Deploy para Estágio
deploy_stage:
  stage: deploy
  script:
    - docker-compose -f docker-compose.stage.yaml up -d
  environment:
    name: staging
    url: http://staging.example.com
    on_stop: stop_stage
  tags:
    - docker

# Ferramenta de Monitoramento Pós-Implantação
monitor:
  stage: deploy
  script:
    - echo "Instalando ferramentas de monitoramento..."
    - docker run --rm -d monitoring-tool:latest  # Substitua pela ferramenta de monitoramento adequada
  tags:
    - docker

# Cleanup de Revisão
stop_review:
  stage: review
  script:
    - docker-compose down
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - docker

# Cleanup de Estágio
stop_stage:
  stage: deploy
  script:
    - docker-compose down
  when: manual
  environment:
    name: staging
    action: stop
  tags:
    - docker
