services:
  web:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    restart: always
    user: "root"
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    user: "root"
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus