filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log  

output.elasticsearch:  
  hosts: ["localhost:9200"]  
  username: "root"
  password: "root"  

setup.kibana:
  host: "localhost:5601"
